### ISSUE TITLE
 [ERROR] Could not load 'plugins/AdvancedCustomMenu.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: AdvancedCustomItemAPI at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:220) [minecraft_server.jar:git-Spigot-093165d-cb3d14c] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [minecraft_server.jar:git-Spigot-093165d-cb3d14c] at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [minecraft_server.jar:git-Spigot-093165d-cb3d14c] at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [minecraft_server.jar:git-Spigot-093165d-cb3d14c] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

### ISSUE THREAD

**Issue by acrospate** [SuperRonanCraft/AdvancedCustomMenu#29]
**Plugin Version**:

**Issue Type**:

**Error**:

**Possible solution**:

**Comments/More info**:

**Comment by SuperRonanCraft** [comment]
Please read the plugin page and download all the dependencies needed to use the plugin :)
